=== gbv/jskos/item.schema.json
{
  "$id": "https://gbv.github.io/jskos/item.schema.json",
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "JSKOS Item",
  "description": "named entities",
  "type": "object",
  "definitions": {
    "itemSet": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "$ref": "#"
          }
        ]
      }
    },
    "language-tag": {
      "type": "string",
      "pattern": "^([a-z]{1,8}(-[a-z0-9]{1,8})*-?|-)$"
    },
    "language-map": {
      "type": "object",
      "patternProperties": {
        "^([a-z]{1,8}(-[a-z0-9]{1,8})*-?|-)$": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "language-map-of-lists": {
      "type": "object",
      "patternProperties": {
        "^([a-z]{1,8}(-[a-z0-9]{1,8})*-?|-)$": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "additionalProperties": false
    },
    "location": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "Point",
            "MultiPoint",
            "LineString",
            "MultiLineString",
            "Polygon",
            "MultiPolygon"
          ]
        }
      },
      "required": [
        "type"
      ],
      "additionalProperties": true
    },
    "address": {
      "type": "object",
      "properties": {
        "street":   { "type": "string" },
        "ext":      { "type": "string" },
        "pobox":    { "type": "string" },
        "locality": { "type": "string" },
        "region":   { "type": "string" },
        "code":     { "type": "string" },
        "country":  { "type": "string" }
      },
      "additionalProperties": false
    },
    "media": {
      "description": "Media based on IIIF Manifest Data Model",
      "type": "object",
      "properties": {
        "type": {
          "const": "Manifest"
        },
        "items": {
          "type": "array"
        }
      },
      "additionalProperties": true,
      "required": [
        "type",
        "items"
      ]
    }
  },
  "allOf": [
    {
      "$ref": "resource.schema.json"
    }
  ],
  "properties": {
    "url": {
      "description": "URL of a page with information about the item",
      "$ref": "resource.schema.json#/definitions/url"
    },
    "notation": {
      "description": "list of notations",
      "$ref": "resource.schema.json#/definitions/list"
    },
    "prefLabel": {
      "description": "preferred labels, index by language",
      "$ref": "#/definitions/language-map"
    },
    "altLabel": {
      "description": "alternative labels, indexed by language",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "hiddenLabel": {
      "description": "hidden labels, indexed by language",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "scopeNote": {
      "description": "see SKOS Documentary Notes",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "definition": {
      "description": "see SKOS Documentary Notes",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "example": {
      "description": "see SKOS Documentary Notes",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "historyNote": {
      "description": "see SKOS Documentary Notes",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "editorialNote": {
      "description": "see SKOS Documentary Notes",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "changeNote": {
      "description": "see SKOS Documentary Notes",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "note": {
      "description": "see SKOS Documentary Notes",
      "$ref": "#/definitions/language-map-of-lists"
    },
    "startDate": {
      "description": "date of birth, creation, or estabishment of the item",
      "$ref": "resource.schema.json#/definitions/edtf"
    },
    "endDate": {
      "description": "date death or resolution of the item",
      "$ref": "resource.schema.json#/definitions/edtf"
    },
    "relatedDate": {
      "description": "other date somehow related to the item (deprecated, use relatedDates instead)",
      "$ref": "resource.schema.json#/definitions/edtf"
    },
    "relatedDates": {
      "description": "other date somehow related to the item (deprecated, use relatedDates instead)",
      "type": "array",
      "items": {
        "$ref": "resource.schema.json#/definitions/edtf"
      }
    },
    "location": {
      "description": "geographic location of the item",
      "$ref": "#/definitions/location"
    },
    "startPlace": {
      "description": "where an item started (e.g. place of birth)",
      "$ref": "concept.schema.json#/definitions/conceptSet"
    },
    "endPlace": {
      "description": "where an item ended (e.g. place of death)",
      "$ref": "concept.schema.json#/definitions/conceptSet"
    },
    "place": {
      "description": "other relevant place(s) of the item",
      "$ref": "concept.schema.json#/definitions/conceptSet"
    },
    "address": {
      "description": "geographic location of the item",
      "$ref": "#/definitions/address"
    },
    "replacedBy": {
      "description": "Related items that supplant, displace, or supersede the described item",
      "$ref": "#/definitions/itemSet"
    },
    "subject": {
      "description": "what this item is about (e.g. topic)",
      "$ref": "concept.schema.json#/definitions/conceptSet"
    },
    "subjectOf": {
      "description": "resources about this item (e.g. documentation)",
      "$ref": "concept.schema.json#/definitions/conceptSet"
    },
    "source": {
      "description": "sources from which the described resource is derived",
      "$ref": "concept.schema.json#/definitions/conceptSet"
    },
    "depiction": {
      "description": "list of image URLs depicting the item",
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "$ref": "resource.schema.json#/definitions/url"
          }
        ]
      }
    },
    "media": {
      "description": "audiovisual or other digital content representing the item",
      "type": "array",
      "items": {
        "$ref": "#/definitions/media"
      }
    },
    "version": {
      "description": "version number",
      "type": "string"
    },
    "versionOf": {
      "description": "items which this item is a version or edition of",
      "$ref": "#/definitions/itemSet"
    },
    "tool": {
      "description": "Tool used to create or manage the item",
      "$ref": "#/definitions/itemSet"
    },
    "issueTracker": {
      "description": "Issue tracker for this item",
      "$ref": "#/definitions/itemSet"
    },
    "issue": {
      "description": "Specific issue for this item",
      "$ref": "#/definitions/itemSet"
    },
    "guidelines": {
      "description": "Standards or guidelines followed in creation of this item",
      "$ref": "#/definitions/itemSet"
    }
  }
}

=== gbv/jskos/examples/example.item.json
{
  "startDate": "Y-12424",
  "endDate": "2016/2023",
  "relatedDate": "2012T12:07",
  "relatedDates": ["2007-03-01T13:00:00Z","-2012","-0043-05-22","2001-21"],
  "issue": [ { "uri": "https://github.com/gbv/jskos/issues/154" } ],
  "issueTracker": [ { "uri": "https://github.com/gbv/jskos/issues" } ],
  "guidelines": [ { "uri": "https://github.com/gbv/jskos#" } ]
}
