=== gbv/jskos/schemas/mapping.schema.json
{
  "$id": "https://gbv.github.io/jskos/mapping.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "JSKOS Concept Mapping",
  "description": "A mapping represents a mapping between concepts of two concept schemes. It consists two concept bundles with additional metadata not fully defined yet.",
  "type": "object",
  "definitions": {
    "set": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "$ref": "#"
          }
        ]
      }
    }
  },
  "allOf": [
    {
      "$ref": "item.schema.json"
    }
  ],
  "properties": {
    "from": {
      "description": "concepts mapped from",
      "$ref": "bundle.schema.json"
    },
    "to": {
      "description": "concepts mapped to",
      "$ref": "bundle.schema.json"
    },
    "fromScheme": {
      "description": "source concept scheme",
      "$ref": "scheme.schema.json"
    },
    "toScheme": {
      "description": "target concept scheme",
      "$ref": "scheme.schema.json"
    },
    "mappingRelevance": {
      "description": "numerical value between 0 and 1 (experimental)",
      "type": "number",
      "minimum": 0,
      "maximum": 1
    }
  },
  "required": [
    "from",
    "to"
  ]
}

=== gbv/jskos/examples/ddc-gnd-2.mapping.json
{
    "fromScheme": {"uri":"http://dewey.info/scheme/edition/e22/"},
    "from": {
        "memberSet": [ {
            "uri": "http://dewey.info/class/612.112/e22/",
            "notation": ["612.112"]
        } ]
    },
    "toScheme": {"uri":"http://d-nb.info/gnd/7749153-1"},
    "to": {
        "memberChoice": [ {
            "uri": "http://d-nb.info/gnd/4074195-3",
            "prefLabel": { "de": "Leukozyt" }
          },{
            "uri": "http://d-nb.info/gnd/4141893-1",
            "prefLabel": { "de": "Alkalische Leukozytenphosphatase" }
          },{
            "uri": "http://d-nb.info/gnd/7606617-4",
            "prefLabel": { "de": "Blutlymphozyt" }
          },{
            "uri": "http://d-nb.info/gnd/4158047-3",
            "prefLabel": { "de": "Granulozyt" }
          },{
            "uri": "http://d-nb.info/gnd/4227943-4",
            "prefLabel": { "de": "Leukozytenadh√§sion" }
          },{
            "uri": "http://d-nb.info/gnd/4166696-3",
            "prefLabel": { "de": "Leukozytenphosphatase" }
          },{
            "uri": "http://d-nb.info/gnd/4285013-7",
            "prefLabel": { "de": "Monozyt" }
        } ]
    },
    "mappingRelevance": 0.5
}
